import type { Metadata } from 'next';
import '@/styles/fonts.css';
import '@/styles/main.css';

import NavBar from '@/components/navbar';
import AuthProvider from '@/components/provider';

export const metadata: Metadata = {
  title: 'Remoto',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en_UK' className='antialiased' suppressHydrationWarning={true}>
      <body className='bg-white text-slate-500' suppressHydrationWarning={true}>
        <AuthProvider>
          <div className='isolate'>
            <NavBar />
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
