import MainNav from '@/components/MainNav';
import '@/styles/fonts.css';
import '@/styles/main.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Remoto',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <head>
        <link rel='shortcut icon' href='/remoto.svg' type='image/x-icon' />
      </head>
      <body
        className='flex flex-col bg-white font-sans text-slate-500 dark:bg-slate-900 dark:text-slate-400'
        suppressHydrationWarning
      >
        <MainNav />
        <div className='flex-1 px-4 pb-8 pt-6 sm:px-6'>{children}</div>
      </body>
    </html>
  );
}
